support for static ip allocation for pod

diff --git a/node-ip-alloc b/node-ip-alloc
--- a/node-ip-alloc
+++ b/node-ip-alloc
@@ -18,9 +18,21 @@ if [ ! -x "/bin/jq" ]; then
     exit 1
 fi
 
-# check which az cli installed and working
+# check if az cli installed and working
 if [ ! -x "/bin/az" ]; then
     echo "/bin/az does not exist or is not executable"
+    exit 1
+fi
+
+# check if crictl installed and working
+if [ ! -x "/bin/crictl" ]; then
+    echo "/bin/crictl does not exist or is not executable"
+    exit 1
+fi
+
+# check if ipcalc installed and working
+if [ ! -x "/bin/ipcalc" ]; then
+    echo "/bin/ipcalc does not exist or is not executable"
     exit 1
 fi
 
@@ -113,6 +125,7 @@ ensure_netns() {
 manage-node-ip() {
     operation=$1
     ip_config_name=$2
+    ip_address=$3
 
     # 检查操作类型和ip-config name是否为空
     if [ -z "$operation" ] || [ -z "$ip_config_name" ]; then
@@ -124,7 +137,13 @@ manage-node-ip() {
 
     # 根据操作类型执行相应的命令
     if [ "$operation" == "create" ]; then
-        result=$(/bin/az network nic ip-config create -g $NODE_RG_NAME --nic-name $NODE_NIC_NAME --name $ip_config_name -o json)
+        # 根据ip_address是否有值来决定是否添加--private-ip-address选项
+        if [ -n "$ip_address" ]; then
+            result=$(/bin/az network nic ip-config create -g $NODE_RG_NAME --nic-name $NODE_NIC_NAME --name $ip_config_name --private-ip-address $ip_address -o json)
+        else
+            result=$(/bin/az network nic ip-config create -g $NODE_RG_NAME --nic-name $NODE_NIC_NAME --name $ip_config_name -o json)
+        fi
+
         if [ $? -ne 0 ]; then
             echo "az create node ip failed"
             exit 1
@@ -152,6 +171,31 @@ manage-node-ip() {
     else
         echo "Invalid operation: $operation"
         exit 1
+    fi
+}
+
+# 获取pod的静态IP地址注解
+get_pod_static_ip_annotation() {
+    if [ $# -ne 1 ]; then
+        echo "Usage: get_pod_static_ip_annotation <pod_id>"
+        return 1
+    fi
+
+    local pod_id=$1
+    local pod_info=$(crictl inspectp $pod_id)
+
+    local node_ip_alloc_method=$(echo $pod_info | jq -r '.status.annotations."node-ip-alloc-method"')
+    if [ "$node_ip_alloc_method" == "static" ]; then
+        ip_address=$(echo $pod_info | jq -r '.status.annotations."node-ip-alloc-ipv4-address"')
+
+        # 校验IP地址的格式
+        if [[ $ip_address =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo $ip_address
+            return 0
+        else
+            echo "Invalid IP address format: $ip_address"
+            return 1
+        fi
     fi
 }
 
@@ -190,6 +234,12 @@ fi
 case $CNI_COMMAND in
 ADD)
 
+#get subnet mask bit , gateway and dns
+mask_bit=17
+gateway_ip=10.0.128.1
+dns_ip=10.96.0.10
+subnet_cidr=10.0.128.0/17
+
 #get the right ip config name from $CNI_ARGS
 ip_config_name=$(get_ip_config_name "$CNI_ARGS")
 if [ $? -ne 0 ]; then
@@ -197,18 +247,27 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-#allocate node ip 并返回ip地址到变量
-manage-node-ip create $ip_config_name
+# 获取CRICTL POD ID
+local crictl_pod_id=${CNI_ARGS#*K8S_POD_INFRA_CONTAINER_ID=}
+crictl_pod_id=${K8S_POD_INFRA_CONTAINER_ID%%;*}
+
+# 获取pod的静态IP地址注解
+get_pod_static_ip_annotation $crictl_pod_id
+
+echo "got ip_address: $ip_address from pod annotation, if it is empty, will allocate a dynamic one from subnet"
+
+# 检查ip_address是否有值
+if [ -n "$ip_address" ]; then
+    manage-node-ip create $ip_config_name $ip_address
+else
+    manage-node-ip create $ip_config_name
+fi
+
 if [ $? -ne 0 ]; then
     echo "Failed to allocate node ip"
     exit 1
 fi
 
-#get subnet mask bit , gateway and dns
-mask_bit=17
-gateway_ip=10.0.128.1
-dns_ip=10.96.0.10
-subnet_cidr=10.0.128.0/17
 
 #获取容器的网络命名空间
 CNI_NETNS_NAME=$(basename $CNI_NETNS)
