1.  optimization for log output 2.  get kubelet conf from cni config instead of hard code

diff --git a/node-ip-alloc b/node-ip-alloc
--- a/node-ip-alloc
+++ b/node-ip-alloc
@@ -5,9 +5,7 @@ if [[ ${DEBUG} -gt 0 ]]; then set -x; fi
 exec 3>&1 # make stdout available as fd 3 for the result
 exec &>> /var/log/node-ip-alloc-plugin.log
 
-echo "CNI node-ip-alloc stars: $(date) "
-echo "CNI command: $CNI_COMMAND"
-echo "CNI ARGS: $CNI_ARGS"
+echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") GOT CNI command: $CNI_COMMAND WITH ARGS: $CNI_ARGS"
 
 stdin=`cat /dev/stdin`
 echo "stdin: $stdin"
@@ -45,6 +43,8 @@ flock -x 200 || {
     flock -x 200
 }
 
+echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") Processing CNI command: $CNI_COMMAND WITH ARGS: $CNI_ARGS"
+
 # 定义环境变量文件路径
 ENV_FILE="/etc/kubernetes/centos-k8s-cluster.env"
 
@@ -71,6 +71,17 @@ check_env "NODE_RG_NAME"
 
 # 如果所有环境变量都不为空，打印成功消息
 echo "All environment variables are set"
+
+# 定义一个函数来获取kubelet配置文件路径
+get_kubeletconf {
+  local kubeletconf=$(jq -r '.kubeletconf' < /dev/stdin)
+  if [[ -z "$kubeletconf" ]]; then
+    echo "Error: kubeletconf is empty" >&2
+    return 1
+  fi
+  echo $kubeletconf
+}
+
 
 get_ip_config_name() {
     local cni_args=$1
@@ -239,7 +250,7 @@ mask_bit=17
 gateway_ip=10.0.128.1
 dns_ip=10.96.0.10
 subnet_cidr=10.0.128.0/17
-kubeconffile="/etc/kubernetes/kubelet.conf"
+kubeconffile=$( echo $stdin |get_kubeletconf )
 
 #get the right ip config name from $CNI_ARGS
 ip_config_name=$(get_ip_config_name "$CNI_ARGS")
